name: tenor_client
description: Tenor client for GIFs
version: 0.1.6
homepage: https://github.com/deckblue/tenor_client
repository: https://github.com/deckblue/tenor_client

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  freezed_annotation: ^2.2.0
  http: ^1.1.0
  json_annotation: ^4.8.1
  json_serializable: ^6.6.1
dev_dependencies:
  build_runner: ^2.3.3
  freezed: ^2.3.2
  test: ^1.19.2
  very_good_analysis: ^5.1.0
